# Mostrar apenas as queries SQL executadas e o tempo
org.slf4j.simpleLogger.defaultLogLevel=warn
org.slf4j.simpleLogger.log.jdbc.sqlonly=info
org.slf4j.simpleLogger.log.jdbc.sqltiming=info
org.slf4j.simpleLogger.showDateTime=true
org.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss
